# Rule types that drive HTML parser behavior
# INLINE inline element
# GROUP group element
# EXCLUDE exclude this element and all children
# INCLUDE exceptions to the exclude rules
# TEXTUNIT make this element a textunit with skeleton before/after
# PRESERVE_WHITESPACE turn on preserve whitespace.
# SCRIPT Embedded scripting languatge - pass to another extractor
# SERVER Embedded server language tags such as JSP, PHP, Mason etc.
# ATTRIBUTE the rule lists an attribute, not an element
# ATTRIBUTES_ONLY only attribute is translatable or localizable 

#********************************************************************************************* 
# Operators for attribute value compare
#
# Rules are of the form: 
# TO_EXTRACT_ATTRIBUTE:[IF_HAS_ATTRIBUTE, OPERATOR, VALUE]
# 'content':['http-equiv', EQUALS, 'keywords']
#
# This rule would read:
# extract the value of 'content' if the value of 'http-equiv' equals 'keywords'
#
# Multiple attribute values may be included in a list:
# 'content':['http-equiv', EQUALS, ['content-language', 'content-type']]
#
# This rule would be read: 
# extract the value of 'content' if the value of 'http-equiv' equals 'content-language' or 'content-type' 
#*******************************************************************************************/

# EQUALS
# NOT_EQUALS 
# MATCH regex match. Must match the entire attribute value

# test group rules
table: 
  ruleTypes: [GROUP]  

tr:
  ruleTypes: [GROUP]  

td:
  ruleTypes: [GROUP]  

ul:
  ruleTypes: [GROUP]  

li:
  ruleTypes: [GROUP]  

# test TextUnit rules
p:
  ruleTypes: [TEXTUNIT]  

# exclude/include test
exclude:
  ruleTypes: [EXCLUDE]  

include:
  ruleTypes: [INCLUDE]  

# attributes that occur on many elements
title:
  ruleTypes: [ATTRIBUTE]
  onlyTheseElements: []
  allElementsExcept: [base, basefront, head, html, meta, param, script, title]

# only attributes are localizable or translatable 
meta:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: {content: [http-equiv, EQUALS, keywords], name: ~}
  localizableAttributes: {content: [http-equiv, EQUALS, [content-language, content-type]]}
  
area:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [accesskey, area]
  
isindex:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [prompt]
  
legend:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [accesskey]

option:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [label, value]
  
optgroup:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [label]
  
th:
  ruleTypes: [ATTRIBUTES_ONLY]
  translatableAttributes: [abbr]

# inline tags
a:
  ruleTypes: [INLINE]
  translatableAttributes: [title, accesskey]

abbr:
  ruleTypes: [INLINE]

acronym:
  ruleTypes: [INLINE]

acronym:
  ruleTypes: [INLINE]

applet:
  ruleTypes: [INLINE]
  translatableAttributes: [alt]

acronym:
  ruleTypes: [INLINE]

b:
  ruleTypes: [INLINE]
  
bdo:
  ruleTypes: [INLINE]

big:
  ruleTypes: [INLINE]

blink:
  ruleTypes: [INLINE]
 
br:
  ruleTypes: [INLINE]
 
button:
  ruleTypes: [INLINE]
  translatableAttributes: [accesskey, value]
 
cite:
  ruleTypes: [INLINE]
 
code:
  ruleTypes: [INLINE]
 
del:
  ruleTypes: [INLINE]

dfn:
  ruleTypes: [INLINE]
 
em:
  ruleTypes: [INLINE]

embed:
  ruleTypes: [INLINE]
 
font:
  ruleTypes: [INLINE]

i:
  ruleTypes: [INLINE]

iframe:
  ruleTypes: [INLINE]
 
img:
  ruleTypes: [INLINE]
  translatableAttributes: [title, alt]

input:
  ruleTypes: [INLINE]
  translatableAttributes: [accesskey, alt, value]
# value if type equals button, default, submit, reset
# title if type equals button, default, submit, reset
 
ins:
  ruleTypes: [INLINE]

acronym:
  ruleTypes: [INLINE]
 
kbd:
  ruleTypes: [INLINE]

label:
  ruleTypes: [INLINE]
  translatableAttributes: [accesskey]
 
li:
  ruleTypes: [GROUP]
  translatableAttributes: [value]

map:
  ruleTypes: [INLINE]

nobr:
  ruleTypes: [INLINE]
 
object:
  ruleTypes: [INLINE]
  translatableAttributes: [standby]

param:
  ruleTypes: [INLINE]
  translatableAttributes: [value]
 
q:
  ruleTypes: [INLINE]
 
s:
  ruleTypes: [INLINE]

samp:
  ruleTypes: [INLINE]

small:
  ruleTypes: [INLINE]

select:
  ruleTypes: [INLINE]
 
span:
  ruleTypes: [INLINE]

spacer:
  ruleTypes: [INLINE]
 
strike:
  ruleTypes: [INLINE]

strong:
  ruleTypes: [INLINE]

sub:
  ruleTypes: [INLINE]

sup:
  ruleTypes: [INLINE]

symbol:
  ruleTypes: [INLINE]
 
table:
  ruleTypes: [GROUP]
  translatableAttributes: [summary]
 
textarea:
  ruleTypes: [INLINE]
  translatableAttributes: [accesskey]
 
tt:
  ruleTypes: [INLINE]
 
td:
  ruleTypes: [GROUP]
  translatableAttributes: [abbr]
 
u:
  ruleTypes: [INLINE]

var:
  ruleTypes: [INLINE]
 
wbr:
  ruleTypes: [INLINE]
 
# Ruby inline tags
ruby:
  ruleTypes: [INLINE]

rb:
  ruleTypes: [INLINE]
 
rt:
  ruleTypes: [INLINE]

rc:
  ruleTypes: [INLINE]

rp:
  ruleTypes: [INLINE]

rbc:
  ruleTypes: [INLINE]

rtc:
  ruleTypes: [INLINE]

# Robo help inline tags
symbol:
  ruleTypes: [INLINE]

face:
  ruleTypes: [INLINE]

# Excluded elements
style:
  ruleTypes: [EXCLUDE]

stylesheet:
  ruleTypes: [EXCLUDE]

# javascript etc.
script:
  ruleTypes: [SCRIPT]

# preserve whitespace
pre:
  ruleTypes: [PRESERVE_WHITESPACE]
